- hosts: "{{ server.ip }}"
  user: "{{ server.exec_ansible_username }}"
  become: yes
  tasks:
    - name: Apt update
      apt:
        update_cache: yes
    - name: Install OpenJDK
      apt:
        name:
          - openjdk-{{ server.openjdk_version }}-jdk
          - zip
          - unzip
    - name: Make user 
      user:
        name: minecraft
    - name: Create server dir
      file:
        path: /home/{{ server.exec_minecraft_username }}/servers/{{ server.dirname }}
        state: directory
        recurse: yes
        owner: "{{ server.exec_minecraft_username }}"
        group: "{{ server.exec_minecraft_username }}"
        mode: 0703
    - name: Create temp dir
      file:
        path: /tmp/{{ server.dirname }}
        state: directory
        recurse: yes
        owner: "{{ server.exec_minecraft_username }}"
        group: "{{ server.exec_minecraft_username }}"
        mode: 0703
    - name: Download and unzip modpack file to temp dir
      unarchive:
        src: "{{ server.download_modpack_url }}"
        dest: /tmp/{{ server.dirname }}
        owner: "{{ server.exec_minecraft_username }}"
        group: "{{ server.exec_minecraft_username }}"
        mode: 0703
        remote_src: yes
    - name: Remove nest dir and copy
      copy:
        src: /tmp/{{ server.dirname }}/{{ server.unzipfile_nest_path }}/
        dest: /home/{{ server.exec_minecraft_username }}/servers/{{ server.dirname }}
        owner: "{{ server.exec_minecraft_username }}"
        group: "{{ server.exec_minecraft_username }}"
        directory_mode: true
        mode: 0703
        remote_src: yes
    - name: Signature eula.txt
      copy:
        dest: /home/{{ server.exec_minecraft_username }}/servers/{{ server.dirname }}/eula.txt
        content: eula=true
        owner: "{{ server.exec_minecraft_username }}"
        group: "{{ server.exec_minecraft_username }}"
        mode: 0703
    - name: Make and copy server.properties
      template:
        src: ./server.properties.j2
        dest: /home/{{ server.exec_minecraft_username }}/servers/{{ server.dirname }}/server.properties
        owner: "{{ server.exec_minecraft_username }}"
        group: "{{ server.exec_minecraft_username }}"
        mode: 0703
    - name: Make and copy runserver.service
      template:
        src: ./runserver.service.j2
        dest: /etc/systemd/system/{{ server.dirname }}.service
    - name: Enable runserver.service
      systemd:
        name: "{{ server.dirname }}.service"
        state: restarted
        enabled: yes

